export type RentType = "MONTHLY" | "YEARLY"
export type WaterBillingType = "PER_UNIT" | "FLAT_RATE" | "TIERED"
export type UnitType = "A" | "B" | "C"
export type MaintenanceType =
  | "ELECTRIC"
  | "WATER"
  | "PHONE"
  | "AIR_CONDITIONAL"
  | "FURNITURE"
  | "FIRE_ALARM_SYSTEM"
  | "WATER_LEAKAGE"
  | "FLOOR_WALL"
  | "BATHROOM"
  | "PAINT"
  | "CEMENT_WOOD"
  | "OTHER"
export type MaintenancePriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT"
