apiVersion: v1
kind: Namespace
metadata:
  name: deawkoikid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deawkoikid-fe
  namespace: deawkoikid
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deawkoikid-fe
  template:
    metadata:
      labels:
        app: deawkoikid-fe
    spec:
      containers:
        - name: app
          image: iamyasuomain/deawkoikid_frontend:latest
          imagePullPolicy: Always   
          ports:
            - containerPort: 3000
          env:
            - name: DEAWKOIKID_API_BASE_URL
              value: "http://localhost:30080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: deawkoikid-fe
  namespace: deawkoikid
spec:
  selector:
    app: deawkoikid-fe
  ports:
    - name: http
      port: 3000          
      targetPort: 3000   
      nodePort: 30000
  type: NodePort