name: E2E

on:
  pull_request:
  push:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app -d app_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    env:
      DB_URL: jdbc:postgresql://localhost:5432/app_test
      DB_USERNAME: app
      DB_PASSWORD: password
      JWT_SECRET_BASE64: pC3U3MRYNraVk2gczQoDQ4xXhmWTKlwZEk5nMEkmlDc=
      BE_IMAGE: docker.io/iamyasuomain/deawkoikid_backend:latest
      BE_PORT: 8080

      CYPRESS_BASE_URL: http://localhost:3000
      CI: "true"

    steps:
      - name: Checkout FE
        uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: iamyasuomain
          password: dckr_pat_XQrX6P-88IRVSCrCGnOA3x2ThAw

      - name: Pull & run backend container
        run: |
          docker pull "$BE_IMAGE"
          docker run -d --name be \
            -p ${BE_PORT}:8080 \
            --env SPRING_PROFILES_ACTIVE=test \
            --env SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/app_test \
            --env SPRING_DATASOURCE_USERNAME=app \
            --env SPRING_DATASOURCE_PASSWORD=password \
            --env JWT_SECRET_BASE64=pC3U3MRYNraVk2gczQoDQ4xXhmWTKlwZEk5nMEkmlDc= \
            "$BE_IMAGE"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Enable pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run Frontend
        run: pnpm dev
      - name: Run Cypress E2E
        run: pnpm dlx cypress run --config baseUrl=${CYPRESS_BASE_URL}
